version: '3.7'
services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always
    networks:
      - backend
networks:
  backend: null
