INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES('4', 'Apple', 'Apple iPad Pro 12.9 (2018)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-129-2018.jpg', '2048 x 2732 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('5', 'Apple', 'Apple iPad Pro 11', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-11-2018.jpg', '1668 x 2388 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('6', 'Apple', 'Apple iPhone XS Max', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-xs-max-new1.jpg', '1242 x 2688 pixels', 'Single SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('7', 'Apple', 'Apple iPhone XS', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-xs-new.jpg', '1125 x 2436 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('8', 'Apple', 'Apple iPhone XR', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-xr-new.jpg', '828 x 1792 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('9', 'Apple', 'Apple Watch Series 4', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-series-4-steel.jpg', '448 x 368 pixels', 'eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('10', 'Apple', 'Apple Watch Series 4 Aluminum', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-series-4-aluminum.jpg', '448 x 368 pixels', 'eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('11', 'Apple', 'Apple iPad 9.7 (2018)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-97-2018.jpg', '1536 x 2048 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('12', 'Apple', 'Apple iPhone X', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-x.jpg', '1125 x 2436 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('13', 'Apple', 'Apple iPhone 8 Plus', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-8-plus-new.jpg', '1080 x 1920 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('14', 'Apple', 'Apple iPhone 8', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-8-new.jpg', '750 x 1334 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('15', 'Apple', 'Apple Watch Edition Series 3', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-edition-series3.jpg', '390 x 312 pixels', 'eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('16', 'Apple', 'Apple Watch Series 3', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-series3-.jpg', '390 x 312 pixels', 'eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('17', 'Apple', 'Apple Watch Series 3 Aluminum', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-series3-sport-.jpg', '390 x 312 pixels', 'eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('18', 'Apple', 'Apple iPad Pro 12.9 (2017)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-129-2017.jpg', '2732 x 2048 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('19', 'Apple', 'Apple iPad Pro 10.5 (2017)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-105-2017.jpg', '1668 x 2224 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('20', 'Apple', 'Apple iPad 9.7 (2017)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-97-2017.jpg', '1536 x 2048 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('21', 'Apple', 'Apple Watch Edition Series 2 42mm', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-edition-42mm.jpg', '390 x 312 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('22', 'Apple', 'Apple Watch Edition Series 2 38mm', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-edition-38mm.jpg', '340 x 272 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('23', 'Apple', 'Apple Watch Series 2 42mm', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-42mm.jpg', '390 x 312 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('24', 'Apple', 'Apple Watch Series 2 38mm', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-38mm.jpg', '340 x 272 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('25', 'Apple', 'Apple Watch Series 2 Aluminum 42mm', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-sport-42mm.jpg', '390 x 312 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('26', 'Apple', 'Apple Watch Series 1 Aluminum 42mm', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch1-sport-42mm.jpg', '390 x 312 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('27', 'Apple', 'Apple Watch Series 2 Aluminum 38mm', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-sport-38mm.jpg', '340 x 272 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('28', 'Apple', 'Apple Watch Series 1 Aluminum 38mm', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-sport-38mm.jpg', '340 x 272 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('29', 'Apple', 'Apple iPhone 7 Plus', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-7-plus-r2.jpg', '1080 x 1920 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('30', 'Apple', 'Apple iPhone 7', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-7r4.jpg', '750 x 1334 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('31', 'Apple', 'Apple iPad Pro 9.7 (2016)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-97.jpg', '1536 x 2048 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('32', 'Apple', 'Apple iPhone SE', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-5se-ofic.jpg', '640 x 1136 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('33', 'Apple', 'Apple iPhone 6s Plus', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-6s-plus.jpg', '1080 x 1920 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('34', 'Apple', 'Apple iPhone 6s', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-6s1.jpg', '750 x 1334 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('35', 'Apple', 'Apple iPad Pro 12.9 (2015)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-.jpg', '2048 x 2732 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('36', 'Apple', 'Apple iPad mini 4', 'https://cdn2.gsmarena.com/vv/bigpic/ipad-mini-41.jpg', '1536 x 2048 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('37', 'Apple', 'Apple Watch Edition 42mm (1st gen)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-edition-42mm.jpg', '390 x 312 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('38', 'Apple', 'Apple Watch Edition 38mm (1st gen)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-edition-38mm.jpg', '340 x 272 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('39', 'Apple', 'Apple Watch 42mm (1st gen)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-42mm.jpg', '390 x 312 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('40', 'Apple', 'Apple Watch 38mm (1st gen)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-38mm.jpg', '340 x 272 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('41', 'Apple', 'Apple Watch Sport 42mm (1st gen)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-sport-42mm2.jpg', '390 x 312 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('42', 'Apple', 'Apple Watch Sport 38mm (1st gen)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-sport-38mm.jpg', '340 x 272 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('43', 'Apple', 'Apple iPad Air 2', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-air-2-new.jpg', '1536 x 2048 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('44', 'Apple', 'Apple iPad mini 3', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-mini-3-new.jpg', '1536 x 2048 pixels', 'Nano-SIM eSIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('45', 'Apple', 'Apple iPhone 6 Plus', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-6-plus2.jpg', '1080 x 1920 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('46', 'Apple', 'Apple iPhone 6', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-6-4.jpg', '750 x 1334 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('47', 'Apple', 'Apple iPad Air', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-air.jpg', '1536 x 2048 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('48', 'Apple', 'Apple iPad mini 2', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-mini2.jpg', '1536 x 2048 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('49', 'Apple', 'Apple iPhone 5s', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-5s-ofic.jpg', '640 x 1136 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('50', 'Apple', 'Apple iPhone 5c', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-5c-new2.jpg', '640 x 1136 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('51', 'Apple', 'Apple iPad mini Wi-Fi', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-mini-final.jpg', '768 x 1024 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('52', 'Apple', 'Apple iPad mini Wi-Fi + Cellular', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-mini-final.jpg', '768 x 1024 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('53', 'Apple', 'Apple iPad 4 Wi-Fi', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-3-new.jpg', '1536 x 2048 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('54', 'Apple', 'Apple iPad 4 Wi-Fi + Cellular', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-3-new.jpg', '1536 x 2048 pixels', 'Micro-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('55', 'Apple', 'Apple iPhone 5', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-5-ofic.jpg', '640 x 1136 pixels', 'Nano-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('56', 'Apple', 'Apple iPad 3 Wi-Fi + Cellular', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-3-new.jpg', '1536 x 2048 pixels', 'Micro-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('57', 'Apple', 'Apple iPad 3 Wi-Fi', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-3-new.jpg', '1536 x 2048 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('58', 'Apple', 'Apple iPhone 4s', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-4s-new.jpg', '640 x 960 pixels ', 'Micro-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('59', 'Apple', 'Apple iPad 2 Wi-Fi + 3G', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad2-new.jpg', '768 x 1024 pixels', 'Micro-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('60', 'Apple', 'Apple iPad 2 Wi-Fi', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad2-new.jpg', '768 x 1024 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('61', 'Apple', 'Apple iPad 2 CDMA', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad2-new.jpg', '768 x 1024 pixels', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('62', 'Apple', 'Apple iPhone 4', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-4-ofic-final.jpg', '640 x 960 pixels ', 'Micro-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('63', 'Apple', 'Apple iPhone 4 CDMA', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone4-cdma.jpg', '640 x 960 pixels ', 'Micro-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('64', 'Apple', 'Apple iPad Wi-Fi + 3G', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-original.jpg', '768 x 1024 pixels', 'Micro-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('65', 'Apple', 'Apple iPad Wi-Fi', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-original.jpg', '768 x 1024 pixels', 'No');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('66', 'Apple', 'Apple iPhone 3GS', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-3gs-ofic.jpg', '320 x 480 pixels ', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('67', 'Apple', 'Apple iPhone 3G', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone3g.jpg', '320 x 480 pixels ', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('68', 'Apple', 'Apple iPhone', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone.gif', '320 x 480 pixels ', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('69', 'Ericsson', 'Ericsson R600', 'https://cdn2.gsmarena.com/vv/bigpic/err600.gif', '5 lines', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('70', 'Ericsson', 'Ericsson T68', 'https://cdn2.gsmarena.com/vv/bigpic/ert68.gif', '101 x 80 pixels', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('71', 'Ericsson', 'Ericsson T66', 'https://cdn2.gsmarena.com/vv/bigpic/ert66.gif', '5 lines', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('72', 'Ericsson', 'Ericsson T65', 'https://cdn2.gsmarena.com/vv/bigpic/ert65.gif', '101 x 67 pixels', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('73', 'Ericsson', 'Ericsson T39', 'https://cdn2.gsmarena.com/vv/bigpic/ert39.gif', '101 x 54 pixels', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('74', 'Ericsson', 'Ericsson A3618', 'https://cdn2.gsmarena.com/vv/bigpic/era3618.gif', '4 lines', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('75', 'Ericsson', 'Ericsson T29s', 'https://cdn2.gsmarena.com/vv/bigpic/ert29.gif', '101 x 33 pixels', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('76', 'Ericsson', 'Ericsson R520m', 'https://cdn2.gsmarena.com/vv/bigpic/err520m.gif', '5 lines', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('77', 'Ericsson', 'Ericsson T20e', 'https://cdn2.gsmarena.com/vv/bigpic/ert20e.gif', '101 x 33 pixels', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('78', 'Ericsson', 'Ericsson A2628', 'https://cdn2.gsmarena.com/vv/bigpic/era2628.gif', '4 lines', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('79', 'Ericsson', 'Ericsson T20s', 'https://cdn2.gsmarena.com/vv/bigpic/ert20s.gif', '101 x 33 pixels', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('80', 'Ericsson', 'Ericsson T36', 'https://cdn2.gsmarena.com/vv/bigpic/ert36b.gif', '4 lines', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('81', 'Ericsson', 'Ericsson R380', 'https://cdn2.gsmarena.com/vv/bigpic/err380b.gif', 'Big', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('82', 'Ericsson', 'Ericsson R320', 'https://cdn2.gsmarena.com/vv/bigpic/err320b.gif', '5 lines', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('83', 'Ericsson', 'Ericsson R310s', 'https://cdn2.gsmarena.com/vv/bigpic/err310s.gif', '5 lines', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('84', 'Ericsson', 'Ericsson A2618', 'https://cdn2.gsmarena.com/vv/bigpic/era2618b.gif', '4 lines', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('85', 'Ericsson', 'Ericsson R250s PRO', 'https://cdn2.gsmarena.com/vv/bigpic/err250sb.gif', '4 lines', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('86', 'Ericsson', 'Ericsson T28 World', 'https://cdn2.gsmarena.com/vv/bigpic/ert28wb.gif', '101 x 33 pixels', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('87', 'Ericsson', 'Ericsson T28s', 'https://cdn2.gsmarena.com/vv/bigpic/ert28sb.gif', '101 x 33 pixels', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('88', 'Ericsson', 'Ericsson T18s', 'https://cdn2.gsmarena.com/vv/bigpic/ert18sb.gif', '101 x 33 pixels', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('89', 'Ericsson', 'Ericsson T10s', 'https://cdn2.gsmarena.com/vv/bigpic/ert10sb.gif', '101 x 33 pixels', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('90', 'Ericsson', 'Ericsson A1018s', 'https://cdn2.gsmarena.com/vv/bigpic/er1018sb.gif', '3 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('91', 'Ericsson', 'Ericsson I 888', 'https://cdn2.gsmarena.com/vv/bigpic/eri888b.gif', '3 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('92', 'Ericsson', 'Ericsson SH 888', 'https://cdn2.gsmarena.com/vv/bigpic/ersh888b.gif', '3 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('93', 'Ericsson', 'Ericsson S 868', 'https://cdn2.gsmarena.com/vv/bigpic/ers868b.gif', '3 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('94', 'Ericsson', 'Ericsson GF 788e', 'https://cdn2.gsmarena.com/vv/bigpic/erg788eb.gif', '1 x 10 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('95', 'Ericsson', 'Ericsson GF 788', 'https://cdn2.gsmarena.com/vv/bigpic/ergf788b.gif', '1 x 10 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('96', 'Ericsson', 'Ericsson PF 768', 'https://cdn2.gsmarena.com/vv/bigpic/erpf768b.gif', '1 x 10 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('97', 'Ericsson', 'Ericsson GF 768', 'https://cdn2.gsmarena.com/vv/bigpic/ergf768b.gif', '1 x 10 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('98', 'Ericsson', 'Ericsson GH 688', 'https://cdn2.gsmarena.com/vv/bigpic/ergh688b.gif', '3 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('99', 'Ericsson', 'Ericsson GA 628', 'https://cdn2.gsmarena.com/vv/bigpic/erga628b.gif', '1 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('100', 'Ericsson', 'Ericsson GF 388', 'https://cdn2.gsmarena.com/vv/bigpic/ergf388b.gif', '3 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('101', 'Ericsson', 'Ericsson GH 388', 'https://cdn2.gsmarena.com/vv/bigpic/ergh388b.gif', '3 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('102', 'Ericsson', 'Ericsson GS 337', 'https://cdn2.gsmarena.com/vv/bigpic/ergs337b.gif', '3 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('103', 'Ericsson', 'Ericsson GF 337', 'https://cdn2.gsmarena.com/vv/bigpic/ergf337b.gif', '3 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('104', 'Ericsson', 'Ericsson GH 337', 'https://cdn2.gsmarena.com/vv/bigpic/ergh337b.gif', '3 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('105', 'Ericsson', 'Ericsson GA 318', 'https://cdn2.gsmarena.com/vv/bigpic/erga318b.gif', '1 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('106', 'Ericsson', 'Ericsson GS 18', 'https://cdn2.gsmarena.com/vv/bigpic/ergs18b.gif', '4 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('107', 'Ericsson', 'Ericsson GO 118', 'https://cdn2.gsmarena.com/vv/bigpic/ergo118b.gif', '4 x 12 chars', 'Mini-SIM');
INSERT INTO DEVICE (id, brand, phone, picture, resolution, sim) VALUES ('108', 'Ericsson', 'Ericsson GH 218', 'https://cdn2.gsmarena.com/vv/bigpic/ergh218b.gif', '1 line', 'Mini-SIM');





INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('1', 'No', 'Li-Po 9720 mAh battery (36.71 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('2', 'No', 'Li-Po 7812 mAh battery (29.45 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('3', 'No', 'Li-Ion 3174 mAh battery', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('4', 'No', 'Li-Ion 2658 mAh battery (10.13 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('5', 'No', 'Li-Ion 2942 mAh battery', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('6', 'No', 'Li-Ion battery', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('7', 'No', 'Li-Ion battery', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('8', 'Yes', 'Li-Ion battery (32.4 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('9', 'No', 'Li-Ion 2716 mAh battery (10.35 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('10', 'No', 'Li-Ion 2691 mAh battery (10.28 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('11', 'No', 'Li-Ion 1821 mAh battery (6.96 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('12', 'No', 'Li-Ion 279 mAh battery (1.07 Wh) - 38mm version', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('13', 'No', 'Li-Ion 279 mAh battery (1.07 Wh) - 38mm version', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('14', 'No', 'Li-Ion 279 mAh battery (1.07 Wh) - 38mm version', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('15', 'Yes', 'Li-Ion 10891 mAh battery (41 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('16', 'Yes', 'Li-Ion 8134 mAh battery (30.8 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('17', 'Yes', 'Li-Ion 8827 mAh battery (32.9 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('18', 'No', 'Li-Ion 334 mAh battery (1.27 Wh)', 'Yes with GLONASS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('19', 'No', 'Li-Ion 273 mAh battery (1.03 Wh)', 'Yes with GLONASS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('20', 'No', 'Li-Ion 334 mAh battery (1.27 Wh)', 'Yes with GLONASS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('21', 'No', 'Li-Ion 273 mAh battery (1.03 Wh)', 'Yes with GLONASS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('22', 'No', 'Li-Ion 334 mAh battery (1.27 Wh)', 'Yes with GLONASS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('23', 'No', 'Li-Ion 250 mAh battery (0.94 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('24', 'No', 'Li-Ion 273 mAh battery (1.03 Wh)', 'Yes with GLONASS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('25', 'No', 'Li-Ion 205 mAh battery (0.78 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('26', 'No', 'Li-Ion 2900 mAh battery (11.1 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('27', 'No', 'Li-Ion 1960 mAh battery (7.45 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('28', 'Yes', 'Li-Ion 7306 mAh battery (27.9 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('29', 'Yes', 'Li-Po 1624 mAh battery (6.21 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('30', 'Yes', 'Li-Ion 2750 mAh battery (10.45 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('31', 'Yes', 'Li-Ion 1715 mAh battery (6.91 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('32', 'Yes', 'Li-Ion 10307 mAh battery (38.8 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('33', 'Yes', 'Li-Ion 5124 mAh battery (19.1 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('34', 'No', 'Li-Ion 250 mAh battery (0.94 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('35', 'No', 'Li-Ion 205 mAh battery (0.78 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('36', 'No', 'Li-Ion 250 mAh battery (0.94 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('37', 'No', 'Li-Ion 205 mAh battery (0.78 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('38', 'No', 'Li-Ion 250 mAh battery (0.94 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('39', 'No', 'Li-Ion 205 mAh battery (0.78 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('40', 'Yes', 'Li-Po 7340 mAh battery (27.62 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('41', 'Yes', 'Li-Po 6470 mAh battery (24.3 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('42', 'Yes', 'Li-Po 2915 mAh battery (11.1 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('43', 'Yes', 'Li-Po 1810 mAh battery (6.9 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('44', 'Yes', 'Li-Po 8600 mAh battery (32.4 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('45', 'Yes', 'Li-Po 6470 mAh battery (24.3 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('46', 'Yes', 'Li-Po 1560 mAh battery (5.92 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('47', 'Yes', 'Li-Po 1510 mAh battery (5.73 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('48', 'Yes', 'Li-Po 4490 mAh battery (16.7 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('49', 'Yes', 'Li-Po 4490 mAh battery (16.7 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('50', 'Yes', 'Li-Po 11560 mAh battery (42.5 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('51', 'Yes', 'Li-Po 11560 mAh battery (42.5 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('52', 'Yes', 'Li-Po 1440 mAh battery (5.45 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('53', 'Yes', 'Li-Po 11560 mAh battery (42.5 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('54', 'Yes', 'Li-Po 11560 mAh battery (42.5 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('55', 'Yes', 'Li-Po 1432 mAh battery (5.3 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('56', 'Yes', 'Li-Po 6930 mAh battery (25 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('57', 'Yes', 'Li-Po 6930 mAh battery (25 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('58', 'Yes', 'Li-Po 6930 mAh battery (25 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('59', 'Yes', 'Li-Po 1420 mAh battery', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('60', 'Yes', 'Li-Po 1420 mAh battery', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('61', 'Yes', 'Li-Po 6600 mAh battery (24.8 Wh)', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('62', 'Yes', 'Li-Po 6600 mAh battery (24.8 Wh)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('63', 'Yes', 'Li-Ion battery', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('64', 'Yes', 'Li-Ion battery', 'Yes with A-GPS');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('65', 'Yes', 'Li-Ion battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('66', 'No', 'Removable Li-Ion (BST-20)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('67', 'No', 'Removable Li-Ion battery (BST-14)', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('68', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('69', 'No', 'Removable Li-Ion battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('70', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('71', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('72', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('73', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('74', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('75', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('76', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('77', 'No', 'Removable Li-Po battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('78', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('79', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('80', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('81', 'No', 'Removable NiMH battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('82', 'No', 'Removable battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('83', 'No', 'Removable Li-Po 500 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('84', 'No', 'Removable Li-Po 500 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('85', 'No', 'Removable NiMH 750 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('86', 'No', 'Removable NiMH 750 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('87', 'No', 'Removable NiMH 800 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('88', 'No', 'Removable NiMH 800 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('89', 'No', 'Removable NiMH 800 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('90', 'No', 'Removable NiMH 800 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('91', 'No', 'Removable NiMH 550 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('92', 'No', 'Removable NiMH 550 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('93', 'No', 'Removable NiMH 550 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('94', 'No', 'Removable NiMH 550 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('95', 'No', 'Removable NiMH 1200 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('96', 'No', 'Removable NiMH 1000 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('97', 'No', 'Removable NiMH 915 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('98', 'No', 'Removable NiMH 915 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('99', 'No', 'Removable NiMH 915 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('100', 'No', 'Removable NiMH 915 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('101', 'No', 'Removable NiMH 915 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('102', 'No', 'Removable NiMH 1200 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('103', 'No', 'Removable NiMH 1200 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('104', 'No', 'Removable NiMH 1200 mAh battery', 'No');
INSERT INTO DEVICE_HARDWARE (id, audio_jack, battery, gps) VALUES ('105', 'No', 'Removable NiMH battery', 'No');




INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES('1', '2018 October', '1100');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('2', '2018 October', '880');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('3', '2018 September', '1250');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('4', '2018 September', '1150');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('5', '2018 September', '850');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('6', '2018 September', '700');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('7', '2018 September', '430');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('8', '2018 March', '350');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('9', '2017 September', '1000');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('10', '2017 September', '770');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('11', '2017 September', '700');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('12', '2017 September', '1450');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('13', '2017 September', '700');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('14', '2017 September', '480');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('15', '2017 June', '900');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('16', '2017 June', '730');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('17', '2017 March', '390');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('18', '2016 September', '1500');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('19', '2016 September', '1450');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('20', '2016 September', '700');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('21', '2016 September', '650');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('22', '2016 September', '450');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('23', '2016 September', '300');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('24', '2016 September', '420');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('25', '2016 September', '270');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('26', '2016 September', '690');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('27', '2016 September', '550');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('28', '2016 March', '690');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('29', '2016 March', '300');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('30', '2015 September', '470');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('31', '2015 September', '500');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('32', '2015 September', '850');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('33', '2015 September', '360');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('34', '2014 September', '13000');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('35', '2014 September', '11000');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('36', '2014 September', '700');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('37', '2014 September', '650');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('38', '2014 September', '250');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('39', '2014 September', '250');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('40', '2014 October', '440');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('41', '2014 October', '400');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('42', '2014 September', '420');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('43', '2014 September', '360');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('44', '2013 October', '350');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('45', '2013 October', '270');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('46', '2013 September', '330');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('47', '2013 September', '300');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('48', '2012 October', '200');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('49', '2012 October', '300');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('50', '2012 October', '350');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('51', '2012 October', '500');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('52', '2012 September', '340');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('53', '2012 March', '400');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('54', '2012 March', '290');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('55', '2011 October', '190');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('56', '2011 March', '370');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('57', '2011 March', '200');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('58', '2011 March', '200');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('59', '2010 June', '200');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('60', '2011 January', '150');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('61', '2010 January', '410');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('62', '2010 January', '310');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('63', '2009 June', '110');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('64', '2008 June', '90');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('65', '2007 January', '420');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('66', '2001 Q4', '700');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('67', '2001 Q4', '650');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('68', '2001 Q4', '250');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('69', '2001 Q4', '250');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('70', '2001', '440');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('71', '2001 Q3', '400');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('72', '2001 February', '420');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('73', '2001', '360');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('74', '2001', '350');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('75', '2001', '270');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('76', '2000', '330');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('77', '2000', '300');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('78', '2000', '200');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('79', '2000', '300');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('80', '2000', '350');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('81', '2000', '500');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('82', '2000', '340');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('83', '1999', '400');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('84', '1999', '290');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('85', '1999', '190');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('86', '1999', '370');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('87', '1999', '200');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('88', '1999', '200');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('89', '1998', '200');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('90', '1998', '150');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('91', '1997', '410');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('92', '1997', '310');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('93', '1997', '110');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('94', '1997', '90');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('95', '1996', '420');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('96', '1996', '200');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('97', '1995', '200');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('98', '1995', '150');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('99', '1995', '410');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('100', '1995', '310');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('101', '1995', '110');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('102', '1995', '150');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('103', '1996', '410');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('104', '1995', '310');
INSERT INTO DEVICE_RELEASE (id, announce_date, price_eur) VALUES ('105', '1994', '110');


/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
